function stateIsChanged(state){
    switch(state){
        case "Andaman and Nicobar":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”Nicobar\”>Nicobar</option><option value=\”North and Middle Andaman\”>North and Middle Andaman </option><option value=\”South Andaman\”>South Andaman</option>";
            break;
        case "Andhra Pradesh":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”Anantapur\”>Anantapur</option><option value=\”Chittor\”>Chittor</option><option value=\”Cuddapah\”>Cuddapah</option><option value=\”East Godavari\”>East Godavari</option><option value=\”Guntur\”>Guntur</option><option value=\”Krishna\”>Krishna</option><option value=\”Kurnool\”>Kurnool</option><option value=\”Nellore\”>Nellore</option><option value=\”Prakasam\”>Prakasam</option><option value=\”Srikakulam\”>Srikakulam</option><option value=\”Vijayanagaram\”>Vijayanagaram</option><option value=\” Visakhapatnam\”>Visakhapatnam</option><option value=\” West Godavari\”>West Godavari</option>";
            break;
        case "Arunachal Pradesh":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”Changlang\”>Changlang</option><option value=\”East Kameng\”>East Kameng</option><option value=\” East Siang \”>East Siang</option><option value=\” Kurung Kummey \”>Kurung Kummey</option><option value=\” Lohit \”>Lohit</option><option value=\” Lower Dibang Valley \”>Lower Dibang Valley</option><option value=\” Lower Subansiri \”>Lower Subansiri</option><option value=\” Papum Pore \”>Papum Pore</option><option value=\” Tawang \”>Tawang</option><option value=\” Tirap \”>Tirap</option><option value=\” Upper Siang \”>Upper Siang</option><option value=\” Upper Subansiri \”>Upper Subansiri</option><option value=\” West Kameng \”>West Kameng</option><option value=\” West Siang \”>West Siang</option>";
            break;
        case "Assam":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\” Bangaigaon \”>Bangaigaon</option><option value=\” Barpeta \”>Barpeta</option><option value=\” Cachar \”>Cachar</option><option value=\” Darrang \”>Darrang</option><option value=\” Dhemaji \”>Dhemaji</option><option value=\” Dhubri \”>Dhubri</option><option value=\” Dibrugarh \”>Dibrugarh</option><option value=\” Goalpara \”>Goalpara</option><option value=\” Golaghat \”>Golaghat</option><option value=\” Hailakandi \”>Hailakandi</option><option value=\” Jorhat \”>Jorhat</option><option value=\” Kamrup \”>Kamrup</option><option value=\” Karbi Anglong \”>Karbi Anglong</option><option value=\” Karimganj \”>Karimganj</option><option value=\” Kokrajhar \”>Kokrajhar</option><option value=\” Lakhimpur \”>Lakhimpur</option><option value=\” Mangaldoi \”>Mangaldoi</option><option value=\” Marigaon \”>Marigaon</option><option value=\” Nagaon \”>Nagaon</option><option value=\” Nalbari \”>Nalbari</option><option value=\” North Cachar Hills \”>North Cachar Hills</option><option value=\” Sibsagar \”>Sibsagar</option><option value=\” Sonitpur \”>Sonitpur</option><option value=\” Tinsukia \”>Tinsukia</option>";
            break;
        case "Bihar":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”19\”>Araria</option><option value=\”20\”>Aurangabad</option><option value=\”21\”>Banka</option><option value=\”1\”>Begusarai</option><option value=\”22\”>Bhabhua</option><option value=\”2\”>Bhagalpur</option><option value=\”23\”>Bhojpur</option><option value=\”25\”>Buxar</option><option value=\”55\”>Chhapra</option><option value=\”4\”>Darbhanga</option><option value=\”26\”>East Champaran</option><option value=\”9\”>Gaya</option><option value=\”30\”>Gopalgang</option><option value=\”32\”>Jamui</option><option value=\”33\”>Jehanabad</option><option value=\”11\”>Kaithar</option><option value=\”34\”>Khagaria</option><option value=\”35\”>Kishanganj</option><option value=\”52\”>Luckeesarai</option><option value=\”38\”>Madhepura</option><option value=\”12\”>Madhubani</option><option value=\”39\”>Munghair</option><option value=\”13\”>Muzaffarpur</option><option value=\”40\”>Nalanda</option><option value=\”41\”>Nawada</option><option value=\”14\”>Patna</option><option value=\”15\”>Purnea</option><option value=\”17\”>Rohtas</option><option value=\”44\”>Saharsa</option><option value=\”46\”>Samastipur</option><option value=\”47\”>Saran</option><option value=\”53\”>Sheikhpura</option><option value=\”54\”>Sheohar</option><option value=\”48\”>Sitamarhi</option><option value=\”18\”>Siwan</option><option value=\”49\”>Supaul</option><option value=\”50\”>Vaishali</option><option value=\”51\”>West Chambaran</option>";
            break;
        case "Chandigarh":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Chandigarh</option>";
            break;
        case "Chattisgarh":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”52\”>Balod</option><option value=\”50\”>Balodabazar</option><option value=\”55\”>Balrampur</option><option value=\”18\”>Bastar</option><option value=\”49\”>Bemetara</option><option value=\”16\”>Bijapur</option><option value=\”21\”>Bilaspur</option><option value=\”1\”>Dantewada</option><option value=\”3\”>Dhamtari</option><option value=\”26\”>Durg</option><option value=\”51\”>Gariyaband</option><option value=\”12\”>Jagdalpur</option><option value=\”8\”>Janjgir</option><option value=\”2\”>Jashpur</option><option value=\”13\”>Kabirdham</option><option value=\”4\”>Kanker</option><option value=\”5\”>Kawardha</option><option value=\”56\”>Kondagaon</option><option value=\”6\”>Korba</option><option value=\”7\”>Koria</option><option value=\”9\”>Mahasamund</option><option value=\”53\”>Mungeli</option><option value=\”14\”>Narayanpur</option><option value=\”15\”>North Bastar</option><option value=\”36\”>Raigarh</option><option value=\”10\”>Raipur</option><option value=\”11\”>Rajnandgaon</option><option value=\”48\”>Sukma</option><option value=\”54\”>Surajpur</option><option value=\”47\”>Surguja</option>";
            break;
        case "Dadra and Nagar Haveli":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Dadra &amp; Nagar Haveli</option><option value=\”2\”>Silvassa</option>";
            break;
        case "Daman and Diu":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Daman</option><option value=\”2\”>Diu</option>";
            break;
        case "Goa":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”2\”>North Goa</option><option value=\”1\”>South Goa</option>";
            break;
        case "Gujarat":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Ahmedabad</option><option value=\”15\”>Amreli</option><option value=\”2\”>Anand</option><option value=\”32\”>Aravalli&nbsp;</option><option value=\”3\”>Banaskanth</option><option value=\”5\”>Bharuch</option><option value=\”6\”>Bhavnagar</option><option value=\”28\”>Botad</option><option value=\”29\”>Chhota Udaipur</option><option value=\”7\”>Dahod</option><option value=\”33\”>Dang</option><option value=\”35\”>Devbhumi Dwarka</option><option value=\”17\”>Gandhinagar</option><option value=\”30\”>Gir Somnath</option><option value=\”18\”>Jamnagar</option><option value=\”19\”>Junagarh</option><option value=\”20\”>Kachchh</option><option value=\”8\”>Kheda</option><option value=\”31\”>Mahisagar</option><option value=\”9\”>Mehsana</option><option value=\”27\”>Morbi</option><option value=\”24\”>Narmada</option><option value=\”25\”>Navsari</option><option value=\”21\”>Panchmahals</option><option value=\”10\”>Patan</option><option value=\”26\”>Porbandar</option><option value=\”11\”>Rajkot</option><option value=\”12\”>Sabarkantha</option><option value=\”13\”>Surat</option><option value=\”14\”>Surendranagar</option><option value=\”34\”>Tapi</option><option value=\”16\”>The Dangs</option><option value=\”4\”>Vadodara(Baroda)</option><option value=\”23\”>Valsad</option>";
            break;
        case "Haryana":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Ambala</option><option value=\”10\”>Bhiwani</option><option value=\”2\”>Faridabad</option><option value=\”3\”>Fatehabad</option><option value=\”11\”>Gurgaon</option><option value=\”4\”>Hissar</option><option value=\”19\”>Jhajar</option><option value=\”5\”>Jind</option><option value=\”6\”>Kaithal</option><option value=\”7\”>Karnal</option><option value=\”8\”>Kurukshetra</option><option value=\”12\”>Mahendragarh-Narnaul</option><option value=\”20\”>Mewat</option><option value=\”21\”>Palwal</option><option value=\”13\”>Panchkula</option><option value=\”14\”>Panipat</option><option value=\”15\”>Rewari</option><option value=\”16\”>Rohtak</option><option value=\”9\”>Sirsa</option><option value=\”17\”>Sonipat</option><option value=\”18\”>Yamuna Nagar</option>";
            break;
        case "Himachal Pradesh":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”5\”>Bilaspur</option><option value=\”6\”>Chamba</option><option value=\”7\”>Hamirpur</option><option value=\”1\”>Kangra</option><option value=\”8\”>Kangra (at Dharmashala)</option><option value=\”9\”>Kinnaur (at Kalpa)</option><option value=\”2\”>Kullu</option><option value=\”11\”>Lahul &amp; Spiti</option><option value=\”12\”>Mandi</option><option value=\”13\”>Shimla</option><option value=\”3\”>Sirmore</option><option value=\”4\”>Solan</option><option value=\”15\”>Una</option>";
            break;
        case "Jammu and Kashmir":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”17\”>Akhnoor</option><option value=\”1\”>Anantnag</option><option value=\”7\”>Badgam</option><option value=\”2\”>Baramulla</option><option value=\”8\”>Doda</option><option value=\”16\”>Handwara</option><option value=\”3\”>Jammu</option><option value=\”9\”>Kargil</option><option value=\”10\”>Kathua</option><option value=\”11\”>Kupwara</option><option value=\”12\”>Leh</option><option value=\”13\”>Poonch</option><option value=\”4\”>Pulwama</option><option value=\”15\”>Rajouri</option><option value=\”5\”>Srinagar</option><option value=\”6\”>Udhampur</option>";
            break;
        case "Jharkhand":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”24\”>Bokaro</option><option value=\”53\”>Chatra</option><option value=\”5\”>Deogarh</option><option value=\”6\”>Dhanbad</option><option value=\”7\”>Dumka</option><option value=\”8\”>East Singhbhum</option><option value=\”27\”>Garhwa</option><option value=\”29\”>Giridih</option><option value=\”28\”>Godda</option><option value=\”31\”>Gumla</option><option value=\”10\”>Hazaribagh</option><option value=\”18\”>Jamtara</option><option value=\”36\”>Koderma</option><option value=\”17\”>Latehar</option><option value=\”37\”>Lohardaga</option><option value=\”42\”>Pakur</option><option value=\”43\”>Palamu</option><option value=\”16\”>Ranchi</option><option value=\”45\”>Sahebgang</option><option value=\”19\”>Saraikela(Kharsanwa)</option><option value=\”1\”>Simdega</option><option value=\”52\”>West Singbhum</option>";
            break;
        case "Karnataka":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”25\”>Bagalkot</option><option value=\”1\”>Bangalore</option><option value=\”2\”>Belgaum</option><option value=\”3\”>Bellary</option><option value=\”4\”>Bidar</option><option value=\”5\”>Bijapur</option><option value=\”28\”>Chamrajnagar</option><option value=\”15\”>Chikmagalur</option><option value=\”16\”>Chitradurga</option><option value=\”6\”>Davangere</option><option value=\”7\”>Dharwad</option><option value=\”27\”>Gadag</option><option value=\”17\”>Gulbarga</option><option value=\”18\”>Hassan</option><option value=\”8\”>Haveri</option><option value=\”19\”>Karwar(Uttar Kannad)</option><option value=\”10\”>Kolar</option><option value=\”11\”>Koppal</option><option value=\”20\”>Madikeri(Kodagu)</option><option value=\”21\”>Mandya</option><option value=\”22\”>Mangalore(Dakshin Kannad)</option><option value=\”12\”>Mysore</option><option value=\”14\”>Raichur</option><option value=\”29\”>Ramanagar</option><option value=\”23\”>Shimoga</option><option value=\”24\”>Tumkur</option><option value=\”26\”>Udupi</option>";
            break;
        case "Kerala":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”16\”>Alappuzha</option><option value=\”1\”>Alleppey</option><option value=\”2\”>Calicut</option><option value=\”3\”>Ernakulam</option><option value=\”13\”>Idukki</option><option value=\”4\”>Kannur</option><option value=\”14\”>Kasargod</option><option value=\”5\”>Kollam</option><option value=\”6\”>Kottayam</option><option value=\”7\”>Kozhikode(Calicut)</option><option value=\”8\”>Malappuram</option><option value=\”9\”>Palakad</option><option value=\”15\”>Pathanamthitta</option><option value=\”11\”>Thirssur</option><option value=\”10\”>Thiruvananthapuram</option><option value=\”12\”>Wayanad</option>";
            break;
        case "Lakshadweep":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Kavaratti</option>";
            break;
        case "Madhya Pradesh":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”59\”>Alirajpur</option><option value=\”58\”>Anupur</option><option value=\”57\”>Ashoknagar</option><option value=\”56\”>Badwani</option><option value=\”17\”>Balaghat</option><option value=\”19\”>Betul</option><option value=\”20\”>Bhind</option><option value=\”1\”>Bhopal</option><option value=\”60\”>Burhanpur</option><option value=\”22\”>Chhatarpur</option><option value=\”23\”>Chhindwara</option><option value=\”24\”>Damoh</option><option value=\”49\”>Datia</option><option value=\”2\”>Dewas</option><option value=\”50\”>Dhar</option><option value=\”51\”>Dindori</option><option value=\”4\”>Guna</option><option value=\”5\”>Gwalior</option><option value=\”52\”>Harda</option><option value=\”27\”>Hoshangabad</option><option value=\”6\”>Indore</option><option value=\”7\”>Jabalpur</option><option value=\”28\”>Jhabua</option><option value=\”53\”>Katni</option><option value=\”29\”>Khandwa</option><option value=\”30\”>Khargone</option><option value=\”31\”>Mandla</option><option value=\”32\”>Mandsaur</option><option value=\”33\”>Morena</option><option value=\”34\”>Narsinghpur</option><option value=\”9\”>Neemuch</option><option value=\”35\”>Panna</option><option value=\”37\”>Raisen</option><option value=\”38\”>Rajgarh</option><option value=\”39\”>Ratlam</option><option value=\”40\”>Rewa</option><option value=\”41\”>Sagar</option><option value=\”13\”>Satna</option><option value=\”16\”>Sehore</option><option value=\”43\”>Seoni</option><option value=\”12\”>Shajapur</option><option value=\”44\”>Shehdol</option><option value=\”54\”>Sheopur</option><option value=\”45\”>Shivpuri</option><option value=\”46\”>Sidhi</option><option value=\”61\”>Singroli</option><option value=\”48\”>Tikamgarh</option><option value=\”14\”>Ujjain</option><option value=\”55\”>Umariya</option><option value=\”15\”>Vidisha</option>";
            break;
        case "Maharashtra":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Ahmednagar</option><option value=\”2\”>Akola</option><option value=\”3\”>Amarawati</option><option value=\”19\”>Aurangabad</option><option value=\”20\”>Bandra(E)</option><option value=\”21\”>Beed</option><option value=\”22\”>Bhandara</option><option value=\”4\”>Buldhana</option><option value=\”23\”>Chandrapur</option><option value=\”26\”>Dharashiv(Usmanabad)</option><option value=\”5\”>Dhule</option><option value=\”24\”>Gadchiroli</option><option value=\”34\”>Gondiya</option><option value=\”35\”>Hingoli</option><option value=\”6\”>Jalana</option><option value=\”7\”>Jalgaon</option><option value=\”8\”>Kolhapur</option>	<option value=\”9\”>Latur</option><option value=\”10\”>Mumbai</option><option value=\”11\”>Nagpur</option><option value=\”25\”>Nanded</option><option value=\”12\”>Nandurbar</option><option value=\”13\”>Nashik</option><option value=\”36\”>Osmanabad</option><option value=\”27\”>Parbhani</option><option value=\”14\”>Pune</option><option value=\”28\”>Raigad</option><option value=\”29\”>Ratnagiri</option><option value=\”15\”>Sangli</option><option value=\”30\”>Satara</option><option value=\”16\”>Sholapur</option><option value=\”31\”>Sindhudurg</option><option value=\”17\”>Thane</option><option value=\”33\”>Vashim</option><option value=\”18\”>Wardha</option><option value=\”32\”>Yavatmal</option>";
            break;
        case "Manipur":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”2\”>Bishnupur</option><option value=\”3\”>Chandel</option><option value=\”4\”>Churachandpur</option><option value=\”9\”>Imphal East</option><option value=\”1\”>Imphal West</option><option value=\”5\”>Senapati</option><option value=\”6\”>Tamenglong</option><option value=\”10\”>Tengnoupal</option><option value=\”7\”>Thoubal</option><option value=\”8\”>Ukhrul</option>";
            break;
        case "Meghalaya":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”2\”>East Garo Hills</option><option value=\”8\”>East Jaintia Hills</option><option value=\”1\”>East Khasi Hills</option><option value=\”4\”>Nongpoh (R-Bhoi)</option><option value=\”11\”>North Garo Hills</option><option value=\”5\”>South Garo Hills</option><option value=\”9\”>South West Garo Hills</option><option value=\”10\”>South West Khasi Hills</option><option value=\”6\”>West Garo Hills</option><option value=\”3\”>West Jaintia Hills</option><option value=\”7\”>West Khasi Hills</option>";
            break;
        case "Mizoram":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Aizawl</option><option value=\”5\”>Kolasib</option><option value=\”2\”>Lungli</option><option value=\”4\”>Mamit</option><option value=\”3\”>Saiha</option>";
            break;
        case "Nagaland":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”8\”>Dimapur</option><option value=\”11\”>Kiphire</option><option value=\”1\”>Kohima</option><option value=\”10\”>Longleng</option><option value=\”3\”>Mokokchung</option><option value=\”4\”>Mon</option><option value=\”9\”>Peren</option><option value=\”2\”>Phek</option><option value=\”5\”>Tuensang</option><option value=\”6\”>Wokha</option><option value=\”7\”>Zunheboto</option>";
            break;
        case "NCT of Delhi":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Delhi</option>";
            break;
        case "Odisha":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Angul</option><option value=\”16\”>Balasore</option><option value=\”2\”>Bargarh</option><option value=\”38\”>Berhampur</option><option value=\”3\”>Bhadrak</option><option value=\”39\”>Bhubaneswar</option><option value=\”4\”>Bolangir</option><option value=\”26\”>Boudh</option><option value=\”5\”>Cuttack</option><option value=\”27\”>Deogarh</option><option value=\”17\”>Dhenkanal</option><option value=\”28\”>Gajapati</option><option value=\”18\”>Ganjam</option><option value=\”29\”>Jagatsinghpur</option><option value=\”7\”>Jajpur</option><option value=\”30\”>Jharsuguda</option><option value=\”8\”>Kalahandi</option><option value=\”9\”>Kandhamal</option><option value=\”31\”>Kendrapara</option><option value=\”19\”>Keonjhar</option><option value=\”32\”>Khurda</option><option value=\”10\”>Koraput</option><option value=\”33\”>Malkangiri</option><option value=\”20\”>Mayurbhanja</option><option value=\”35\”>Nayagarh</option><option value=\”12\”>Nowarangpur</option><option value=\”34\”>Nuapada</option><option value=\”13\”>Puri</option><option value=\”14\”>Rayagada</option><option value=\”37\”>Rourkela</option><option value=\”22\”>Sambalpur</option><option value=\”36\”>Sonepur</option><option value=\”23\”>Sundergarh</option></select>";
            break;
        case "Pondicherry":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”4\”>Karaikal</option><option value=\”2\”>Mahe</option><option value=\”1\”>Pondicherry</option><option value=\”3\”>Yanam</option>";
            break;
        case "Punjab":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Amritsar</option><option value=\”20\”>Barnala</option><option value=\”11\”>Bhatinda</option><option value=\”2\”>Faridkot</option><option value=\”12\”>Fatehgarh</option><option value=\”21\”>Fazilka</option><option value=\”3\”>Ferozpur</option><option value=\”4\”>Gurdaspur</option><option value=\”13\”>Hoshiarpur</option><option value=\”14\”>Jalandhar</option><option value=\”5\”>kapurthala</option><option value=\”6\”>Ludhiana</option><option value=\”15\”>Mansa</option><option value=\”7\”>Moga</option><option value=\”19\”>Mohali</option><option value=\”8\”>Muktsar</option><option value=\”17\”>Nawanshahr</option><option value=\”22\”>Pathankot</option><option value=\”9\”>Patiala</option><option value=\”16\”>Ropar (Rupnagar)</option><option value=\”10\”>Sangrur</option><option value=\”18\”>Tarntaran</option>";
            break;
        case "Rajasthan":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Ajmer</option><option value=\”2\”>Alwar</option><option value=\”19\”>Banswara</option><option value=\”3\”>Baran</option><option value=\”20\”>Barmer</option><option value=\”4\”>Bharatpur</option><option value=\”5\”>Bhilwara</option><option value=\”21\”>Bikaner</option><option value=\”6\”>Bundi</option><option value=\”7\”>Chittorgarh</option><option value=\”8\”>Churu</option><option value=\”10\”>Dausa</option><option value=\”22\”>Dholpur</option><option value=\”23\”>Dungarpur</option><option value=\”11\”>Ganganagar</option><option value=\”12\”>Hanumangarh</option><option value=\”13\”>Jaipur</option><option value=\”24\”>Jaisalmer</option><option value=\”25\”>Jalore</option><option value=\”34\”>Jhafarapatan</option><option value=\”26\”>Jhalawar</option><option value=\”14\”>Jhunjunu</option><option value=\”15\”>Jodhpur</option><option value=\”33\”>Karauli</option><option value=\”16\”>Kota</option><option value=\”17\”>Nagaur</option><option value=\”27\”>Pali</option><option value=\”28\”>Rajasamand</option><option value=\”29\”>Sikar</option><option value=\”30\”>Sirohi</option><option value=\”18\”>Swai Madhopur</option><option value=\”31\”>Tonk</option><option value=\”32\”>Udaipur</option>";
            break;
        case "Sikkim":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>East</option><option value=\”2\”>North Sikkim (Mangan)</option><option value=\”3\”>South Sikkim (Namchi)</option><option value=\”4\”>West Sikkim (Gyalsing)</option>";
            break;
        case "Tamil Nadu":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”30\”>Ariyalur</option><option value=\”15\”>Chennai</option><option value=\”1\”>Coimbatore</option><option value=\”2\”>Cuddalore</option><option value=\”12\”>Dharmapuri</option><option value=\”13\”>Dindigul</option><option value=\”3\”>Erode</option><option value=\”4\”>Kancheepuram</option><option value=\”14\”>Karur</option><option value=\”31\”>Krishnagiri</option><option value=\”5\”>Madurai</option><option value=\”16\”>Nagapattinam</option><option value=\”17\”>Nagercoil (Kannyiakumari)</option><option value=\”18\”>Namakkal</option><option value=\”6\”>Perambalur</option><option value=\”20\”>Pudukkottai</option><option value=\”21\”>Ramanathapuram</option><option value=\”22\”>Salem</option><option value=\”23\”>Sivaganga</option><option value=\”7\”>Thanjavur</option><option value=\”19\”>The Nilgiris</option><option value=\”24\”>Theni</option><option value=\”25\”>Thiruchirappalli</option><option value=\”26\”>Thirunelveli</option><option value=\”8\”>Thiruvannamalai</option><option value=\”9\”>Thiruvarur</option><option value=\”27\”>Thiruvellore</option><option value=\”28\”>Tuticorin</option><option value=\”29\”>Vellore</option><option value=\”10\”>Villupuram</option><option value=\”11\”>Virudhunagar</option>";
            break;
        case "Telangana":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”11\”>Adilabad</option><option value=\”2\”>Hyderabad</option><option value=\”21\”>Jagityal</option>	<option value=\”23\”>Kamareddy</option><option value=\”3\”>Karimnagar</option><option value=\”4\”>Khammam</option><option value=\”5\”>Mahbubnagar</option><option value=\”6\”>Medak</option><option value=\”7\”>Nalgonda</option><option value=\”8\”>Nizamabad</option><option value=\”20\”>Ranga Reddy</option><option value=\”22\”>Siddipet</option><option value=\”10\”>Warangal</option>";
            break;
        case "Tripura":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”3\”>Dhalai</option><option value=\”8\”>Gomati</option><option value=\”7\”>Khowai</option><option value=\”4\”>North Tripura</option><option value=\”5\”>Sepahijala</option><option value=\”1\”>South District</option><option value=\”6\”>Unokoti</option><option value=\”2\”>West District</option>";
            break;
        case "Uttar Pradesh":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”1\”>Agra</option><option value=\”31\”>Aligarh</option><option value=\”2\”>Allahabad</option><option value=\”33\”>Ambedkarnagar</option><option value=\”73\”>Auraiya</option><option value=\”34\”>Azamgarh</option><option value=\”35\”>Badaun</option><option value=\”74\”>Baghpat</option><option value=\”3\”>Bahraich</option><option value=\”4\”>Ballia</option><option value=\”75\”>Balrampur</option><option value=\”36\”>Banda</option><option value=\”5\”>Barabanki</option><option value=\”6\”>Bareilly</option><option value=\”37\”>Basti</option><option value=\”38\”>Bhadohi(Sant Ravi Nagar)</option><option value=\”39\”>Bijnor</option><option value=\”40\”>Bulandshahar</option><option value=\”76\”>Chandauli</option><option value=\”77\”>Chitrakut</option><option value=\”42\”>Deoria</option><option value=\”43\”>Etah</option><option value=\”14\”>Etawah</option><option value=\”8\”>Faizabad</option><option value=\”9\”>Farukhabad</option><option value=\”44\”>Fatehpur</option><option value=\”45\”>Firozabad</option><option value=\”78\”>Gautam Budh Nagar</option><option value=\”10\”>Ghaziabad</option><option value=\”47\”>Ghazipur</option><option value=\”48\”>Gonda</option><option value=\”11\”>Gorakhpur</option><option value=\”49\”>Hamirpur</option><option value=\”13\”>Hardoi</option><option value=\”79\”>Hathras</option><option value=\”51\”>Jalaun (Orai)</option><option value=\”15\”>Jaunpur</option><option value=\”52\”>Jhansi</option><option value=\”80\”>Jyotiba Phule Nagar</option><option value=\”81\”>Kannuj</option><option value=\”16\”>Kanpur</option><option value=\”82\”>Kaushambi</option><option value=\”85\”>Khiri (Lakhimpur)</option><option value=\”17\”>Lakhimpur</option><option value=\”18\”>Lalitpur</option><option value=\”19\”>Lucknow</option><option value=\”53\”>Maharajganj</option><option value=\”54\”>Mahoba</option><option value=\”20\”>Mainpuri</option><option value=\”55\”>Mathura</option><option value=\”56\”>Mau(Maunathbhanjan)</option><option value=\”21\”>Meerut</option><option value=\”57\”>Mirzapur</option><option value=\”22\”>Muradabad</option><option value=\”58\”>Muzaffarnagar</option><option value=\”86\”>Oraya</option><option value=\”59\”>Padrauna(Kusinagar)</option><option value=\”24\”>Pillibhit</option><option value=\”61\”>Pratapgarh</option><option value=\”62\”>Raebarelli</option><option value=\”63\”>Rampur</option><option value=\”25\”>Saharanpur</option><option value=\”83\”>Sant Kabir Nagar</option><option value=\”26\”>Shahjahanpur</option><option value=\”84\”>Shravasti</option><option value=\”64\”>Siddharth Nagar</option><option value=\”27\”>Sitapur</option><option value=\”65\”>Sonbhadra</option><option value=\”66\”>Sultanpur</option><option value=\”68\”>Unnao</option><option value=\”30\”>Varanasi</option>";
            break;
        case "Uttrakhand":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”32\”>Almora</option><option value=\”70\”>Bageshwar</option><option value=\”41\”>Chamoli (Gopeshwar)</option><option value=\”71\”>Champawat</option><option value=\”7\”>Dehradoon</option><option value=\”46\”>Garhwal (Pauri)</option><option value=\”1\”>Haldwani</option><option value=\”50\”>Haridwar</option><option value=\”23\”>Nanital</option><option value=\”60\”>Pithoragarh</option><option value=\”72\”>Rudraprayag</option><option value=\”67\”>Tehri Garhwal</option><option value=\”28\”>UdhamSinghNagar</option><option value=\”69\”>Uttarkashi</option>";
            break;
        case "West Bengal":
            document.querySelector("#districtList").innerHTML="<option selected=\”selected\” value=\”0\”>--Select--</option><option value=\”2\”>Bankura</option><option value=\”3\”>Birbhum</option><option value=\”4\”>Burdwan</option><option value=\”5\”>Coochbehar</option><option value=\”6\”>Dakshin Dinajpur</option><option value=\”17\”>Darjeeling</option><option value=\”7\”>Hooghly</option><option value=\”18\”>Howrah</option><option value=\”8\”>Jalpaiguri</option><option value=\”16\”>Kolkata</option><option value=\”9\”>Malda</option><option value=\”10\”>Medinipur(E)</option><option value=\”11\”>Medinipur(W)</option><option value=\”12\”>Murshidabad</option><option value=\”13\”>Nadia</option><option value=\”1\”>North 24 Parganas</option><option value=\”19\”>Puruliya</option><option value=\”15\”>Sounth 24 Parganas</option><option value=\”14\”>Uttar Dinajpur</option>";
            break;
        case "default":
            document.querySelector("#districtList").innerHTML="<option value=\"0\">--Select--</option>";
            break;
        
    }
    
}